apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generation: 1
  labels:
    daemon: node-exporter
    grafanak8sapp: "true"
  name: node-exporter
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      daemon: node-exporter
      grafanak8sapp: "true"
  template:
    metadata:
      labels:
        daemon: node-exporter
        grafanak8sapp: "true"
      name: node-exporter
    spec:
      containers:
      - args:
        - --path.procfs=/proc_host
        - --path.sysfs=/host_sys
        image: quay.io/prometheus/node-exporter:v0.16.0
        imagePullPolicy: IfNotPresent
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: node-exporter
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host_sys
          name: sys
          readOnly: true
        - mountPath: /proc_host
          name: proc
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
