apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: client
    protocol: TCP
    port: 30690
    nodePort: 30690
    targetPort: 9090
  externalTrafficPolicy: Cluster
